# Generated by Django 3.2.15 on 2022-10-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('total_number', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('charge', models.CharField(max_length=10)),
            ],
        ),
    ]
