# Generated by Django 3.2.15 on 2022-10-31 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('std_id', models.CharField(max_length=5, verbose_name='学籍番号')),
                ('sbj_name', models.CharField(max_length=20, verbose_name='科目')),
                ('atd_time', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='出席コマ数')),
            ],
        ),
        migrations.CreateModel(
            name='Sbj',
            fields=[
                ('sbj_name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='科目')),
                ('std_fac', models.CharField(max_length=2, verbose_name='学科')),
                ('std_grd', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='学年')),
                ('curr_cnt', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='現在の授業回数')),
                ('total_cnt', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(30)], verbose_name='授業総数')),
            ],
        ),
        migrations.CreateModel(
            name='Tmt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_week', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='曜日')),
                ('sbj_bgn', models.TimeField(verbose_name='開始時刻')),
                ('std_fac', models.CharField(max_length=2, verbose_name='学科')),
                ('std_grd', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='学年')),
                ('sbj_name', models.CharField(max_length=20, verbose_name='科目')),
            ],
        ),
    ]
