# Generated by Django 3.2.15 on 2022-10-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myroll', '0002_auto_20221023_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attending',
            fields=[
                ('userpk', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
